### ISSUE TITLE
vm2 Sandbox Escape vulnerability

### ISSUE THREAD

**Issue by ajaykarthikr** [release-it/release-it#1024]
Npm is reporting vm2 vulnerability again. I have noticed the packages were updated recently but it seems the issue wasn't resolved. I looked at the vm2 package, the author suggests to use an alternative.
> TL;DR The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to [isolated-vm](https://www.npmjs.com/package/isolated-vm).

Is it possible to fix this issue? This comes from `degenerator` dependency

Severity: critical
vm2 Sandbox Escape vulnerability - GHSA-cchq-frgv-rjh5

Reference: https://github.com/TooTallNate/proxy-agents/issues/218

**Comment by kamal-brill** [comment]
@webpro I understand, but as package it's throwing critical errors when we run `npm audit`. So we are eagerly waiting for this to get resolved.

**Comment by webpro** [comment]
FYI, I'm not a security expert, but if [this explanation](https://github.com/TooTallNate/proxy-agents/issues/218#issuecomment-1636441524) is correct it sounds like the leak can only be exploited when the url (`github.proxy` in release-it) points to a `pac` (proxy auto config) file. If someone has a better understanding of this I'm all ears.

Usually release-it is a `devDependency`, not meant to run in your production environment.

Security tooling is essential, keep assessing the actual risks for your own circumstances.

**Comment by ghiscoding** [comment]
FYI, I also came here because I got security messages from GitHub as well and I did notice it came from `proxy-agent` from a transitive dependency. I then search on `proxy-agent` and found that they indeed worked on addressing the issue via this [PR - Use `quickjs-emscripten` instead of `vm2` to execute PAC file code](https://github.com/TooTallNate/proxy-agents/pull/224), the PR was merged yesterday and it looks like they also released it as `proxy-agent` [release v6.3.0](https://github.com/TooTallNate/proxy-agents/releases/tag/proxy-agent%406.3.0) has the fix. So @webpro you might be able to just update to the latest version of `proxy-agent` and that will hopefully resolve the issue!? Crossing finger 🤞🏻

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v16.1.3. See [Release 16.1.3](https://github.com/release-it/release-it/releases/tag/16.1.3) for release notes._

**Comment by webpro** [comment]
Thanks for your notification, @ghiscoding!
