### ISSUE TITLE
Possible to override bump cmd to use in other language?

### ISSUE THREAD

**Issue by axi92** [release-it/release-it#1143]
I want to use it for dart. And like to override specific hooks.
Like version bumping to do `dart run cider bump patch`.
I have no package.json obviously.

Is something like this possible right now?

**Comment by webpro** [comment]
Yes, that should be possible.

Use debugging an verbose output to see what's going and in what order: https://github.com/release-it/release-it?tab=readme-ov-file#troubleshooting--debugging

Hooks are not something you override, you hook into specific points in the process and execute arbitrary commands. If you need to change or override existing behavior this is either available with existing config options or plugins, and otherwise a new custom plugin is required (plugins can disable or extend existing plugins).

**Comment by axi92** [comment]
Thank you that helped!
If somebody needs that in the future thats the config that I use now:
https://github.com/evva-sfw/abrevva-flutter/blob/02de2e3764bdaca30c5b1726ecaa7b0083b73f98/.release-it.json
But with the pub.dev restrictions on publishing from github I let release-it make the commit and github release including tag pushing.
And then the pushed tag triggers [another workflow](https://github.com/evva-sfw/abrevva-flutter/blob/02de2e3764bdaca30c5b1726ecaa7b0083b73f98/.github/workflows/pub.dev.yml) that does the actual release to dev.pub.
