### ISSUE TITLE
Should version variable be available in git command?

### ISSUE THREAD

**Issue by lorello** [release-it/release-it#547]
I'm using v12.3.5 and trying to use auto-changelog to generate the git changelog message, so I'd like to use a command like:
```
git:
  changelog: "auto-changelog --stdout --template keepachangelog --latest-version ${version}" 
```
But seems that `$version` is not available here.

Tryed also simply using:
```
    changelog: "echo ${version}"
```
but the output is
```
🚀 Let's release XXX (currently at 0.0.1)

Changelog:
[object Object]

? Select increment (next version): (Use arrow keys)
```

Can I use ${version} variable in `git.changelog` command?

**Comment by webpro** [comment]
Indeed, the `{version}` is unfortunately not yet available in `git.changelog`. It's because at that point the next version still needs to be determined by the user if a bump (patch/minor/major/version) wasn't provided. It should be available if you provide this bump (`--increment`) upfront.

The `git.changelog` is used mainly for the CLI to validate the correct version bump, and as a fallback for `[github|gitlab].releaseNotes`.

Please note that, in order to generate a changelog for e.g. the GitHub Release, you can use `github.releaseNotes` for this.

**Comment by lorello** [comment]
Hi @webpro, I can use `gitlab.releaseNotes`, it was just helpful to have a preview of what I'm going to publish in the release, but I understand the problem. Thanks!
