### ISSUE TITLE
pushRepo with git url falling back to https

### ISSUE THREAD

**Issue by zanedev** [release-it/release-it#554]
When I run the release locally with pushRepo specified using a git url it all works but when I run the same release commands on our CI server (Jenkins) it has errors about unable to fetch and it looks like it's using the `https` address even though I specified a `git` url.

**Errors**
```
16:06:39  ERROR Unable to fetch from git@my-gitrepo-url.com/project.git
16:06:39  fatal: could not read Username for 'https://my-gitrepo-url.com': No such device or address
16:06:39  
16:06:39  (node:2154) UnhandledPromiseRejectionWarning: Error: Unable to fetch from git@my-gitrepo-url.com/project.git
16:06:39  fatal: could not read Username for 'https://my-gitrepo-url.com': No such device or address
16:06:39  
```

**Config:**
```
release({
	'non-interactive': true, // ci mode
	verbose: true,
	increment: 'prerelease',
	preReleaseId: 'dev',
	// don't commit anything just create release, tag, and upload the files
	git: {
		commit: false,
		requireCleanWorkingDir: false,
		pushRepo: 'git@my-gitrepo-url.com/project.git', // need to set this specifically for CI
	},
	github: {
		preRelease: true,
		release: true,
		assets: ['dist/*.gz'],
	},
	npm: false,
});
```

**Comment by webpro** [comment]
The `git.pushRepo` is only used for `git push`. The CI environment is doing the clone.

**Comment by zanedev** [comment]
Okay thanks, so is it using a combination of both token and the ci environment to push a release?  I'm confused why it's trying to clone/fetch is that due to relying on the remote tag to bump the version rather than specifying the version in `package.json`?

**Comment by zanedev** [comment]
I guess a better question is how can I achieve release tagging and upload with only using the GH token?

**Comment by webpro** [comment]
> Okay thanks, so is it using a combination of both token and the ci environment to push a release?

To push, it needs to be authorized to do so. It's executing a `git push` as you would do from your own machine. For https url's you need a password, for ssl you need a key.

> I'm confused why it's trying to clone/fetch 

release-it does not clone, but it does execute a a `git fetch` (more useful for local releasing to make sure you have the latest version/tags). I'm surprised that if the repo was just cloned by the CI environment, a fetch would not work? Maybe the clone url contained the username and password?

> is that due to relying on the remote tag to bump the version rather than specifying the version in package.json?

When there's a `package.json`, that `version` is used. Otherwise the Git tag.

> I guess a better question is how can I achieve release tagging and upload with only using the GH token?

Maybe you are conflating pushing tags and GitHub releases? The former is `git push` (with a public key for Git over ssl), the latter is a [GitHub Release](https://github.com/release-it/release-it/blob/master/docs/github-releases.md) with a GitHub API token.

By the way, you can use `--verbose` to see the commands release-it executes. Or `DEBUG=release-it:* release-it [...]` for more details.

**Comment by zanedev** [comment]
Okay thanks for clarification on when the token is needed etc.  You're right I was conflating pushing tags and release, I figured it could all be done using the token and should have read your git instructions more carefully about using the ssh/environment to push a tag etc.

I'll try to remove the tags to get around it for now thanks!

**Comment by zanedev** [comment]
@webpro just curious why does this lib use the environment git, why not use the token and the oktokit rest api for everything with git?  Using the environment git command just adds another layer of setup etc.

**Comment by webpro** [comment]
I think you're conflating Git and GitHub again :)

* Octokit is a client for the GitHub API, to work with GitHub projects. Also note that GitHub is only one service to store Git repositories. E.g. GitLab or even your local file system could host Git repos as well.
* What we need in order to work with Git (e.g. fetch, status, add, commit, tag, push, etc) is a way to execute Git commands from the Node.js environment.

**Comment by zanedev** [comment]
Hmm pretty sure you can do all that with oktokit also..  https://octokit.github.io/rest.js/#octokit-routes-git

But yeah if you're trying to keep it provider agnostic then the easiest and most compatible option would be to use the env git binary so makes sense 👍
