### ISSUE TITLE
ERROR Could not get remote Git url.

### ISSUE THREAD

**Issue by cezarsmpio** [release-it/release-it#570]
Hey, I'm trying to use this lib on CI but it is showing this error when I try to publish it.

```
> release-it "--ci" "--preRelease=draft"

ERROR Could not get remote Git url.
Please add a remote repository.
```

My `.release-it.json`:

```json
{
  "git": {
    "tagName": "v${version}",
    "commitMessage": "chore: [skip-ci] - ${version}"
  },
  "github": {
    "release": true
  },
  "plugins": {
    "@release-it/conventional-changelog": {
      "preset": "angular",
      "infile": "CHANGELOG.md"
    }
  }
}
```

I've already tried to set `git.pushRepo` to`git@github.com:owner/repo.git` or `https://github.com/owner/repo.git`. When I use some URL but `origin`, I get the following error:

```
ERROR Unable to fetch from MY_URL
fatal: No remote repository specified.  Please, specify either a URL or a
remote name from which new revisions should be fetched.
```

My `GITHUB_TOKEN` is present.

**Comment by webpro** [comment]
Apparently the Git remote url is not set properly. The CI environment is cloning/providing the repository, and should set this. Otherwise you could do a `git remote add [...]` yourself in the CI release script before executing `release-it`.

With `git.pushRepo` the repo to `git push` is set (as opposed to where the original repo is updated from with `git fetch`).

Please see [Git](https://github.com/release-it/release-it/blob/master/docs/git.md) and [GitHub Releases](https://github.com/release-it/release-it/blob/master/docs/github-releases.md) for more details. Use `--verbose` to see what commands `release-it` executes including their output.
