### ISSUE TITLE
${version} resolves to [object Object] in hooks

### ISSUE THREAD

**Issue by jgentes** [release-it/release-it#582]
The actual version number that it uses in the git tag and commit message are correct, so it's got something to do with hooks. 

```
/mnt/c/dev/boss - [release-test] $ release-it
✔ echo module.exports = {version: "'"[object Object]"'"} > $(git rev-parse --show-toplevel)/VERSION
� Let's release boss (8.1.7...8.1.8)
Changelog:
* release: v8.1.8 (33b154a3)
Empty changeset
⠙ Git commitWARNING No changes to commit. The latest commit will be tagged.
✔ Git commit
✔ Git tag
� Done (in 3s.)
```

Here's the release-it-.json:
```
{
  "non-interactive": true,
  "npm": false,
  "hooks": {
    "before:init": "echo module.exports = {version: \"'\"${version}\"'\"} > $(git rev-parse --show-toplevel)/VERSION"
  },
  "git": {
    "requireCleanWorkingDir": false,
    "commitMessage": "release: v${version}",
    "commitArgs": "--no-verify",
    "tagName": "v${version}",
    "push": false
  }
}
```

Thanks for your work Lars. I know it's a labor of love!

**Comment by webpro** [comment]
The `before:init` hook is executed before release-it does anything interesting. To get to e.g. failing tests or linting issues as fast as possible.

The first hook hook that runs after `version` (and `latestVersion`) are determined is `before:beforeBump`. But to make it less confusing I suggest to just use `before:bump`. I was about to improve this part of the docs, so thanks for reminding me.

> Thanks for your work Lars. I know it's a labor of love!

It's my pleasure, thank you for using and stretching release-it to lengths!

**Comment by jgentes** [comment]
Thanks, using `after:bump` fixed it, My current config:

```
{
  "non-interactive": true,
  "npm": false,
  "hooks": {
    "after:bump": "echo module.exports = {version: \"'\"${version}\"'\"} > $(git rev-parse --show-toplevel)/VERSION"
  },
  "git": {
    "requireCleanWorkingDir": false,
    "commitMessage": "release: v${version}",
    "commitArgs": "--no-verify",
    "tagName": "v${version}",
    "push": false
  }
}
```

**Comment by leandromoreirati** [comment]
Dear ... thank you for your time and attention, thanks to your tip I managed to find the errors that were in the configuration:

1) Incorrect hook configuration replaces:
```
"after: release": "npx auto-changelog --commit-limit false https://raw.githubusercontent.com/release-it/release-it/master/conf/keepachangelog.hbs"
```
Per:
```
"after: bump": "npx auto-changelog -p /my_user_home/package.json"
```
And he started to generate the file and commit it, which led me to the second error:

2) Wrong understanding on my part because of the settings, because in the initial understanding I had, when I use (`.release-it.json`) I would not need to use the `package.json` configuration file, when creating the `package.json` file the problem has been fully resolved.

One last doubt, using the `package.json` file, I have to manually insert the `Release version`, is there any way to automate this process, I tried instead of the version to insert the variable version (`"version": "$ {version}"`) but it did not work.

Thanks!
