### ISSUE TITLE
No changelog for github release with @release-it/conventional-changelog plugin

### ISSUE THREAD

**Issue by rchl** [release-it/release-it#601]
Either I'm doing something wrong or it's a bug but when I've tried to use `@release-it/conventional-changelog` plugin with `github.release` enabled, the github release didn't include the changelog.

My `.release-it.js` configuration:
```js
module.exports = {
  plugins: {
    '@release-it/conventional-changelog': {
      preset: 'conventionalcommits',
    },
  },
  git: {  // Currently just testing so avoiding changing repo
    commit: false,
    push: false,
  },
  npm: false,  // Ignore bumping package.json and npm publish
  github: {
    release: true,
  },
};
```

I'm using the `@release-it/conventional-changelog` plugin since I want the release version to be auto-suggested and I want changelogs to be generated based on conventional commits convention. The latter part is not working. Here is the output I'm getting (with `DEBUG="release-it:conv*"` logging enabled):

```
Changelog:
* Add release-it (4598757)
* chore(tests): use core-js@3 when building Nuxt (deeb607)
* chore(deps): pin dependency @nuxtjs/eslint-config-typescript to 1.0.2 (#604) (69c13a1)
* chore: switch to `@nuxtjs/eslint-config-typescript` for eslint configuration (#600) (fe0c163)
* feat: Added cookieDomain option to override locale cookie's domain (#599) (7525cd7)
* chore(deps): lock file maintenance (#576) (3eb9fdb)
* chore(deps): update dependency chromedriver to v80 (#584) (c0e9a90)
* chore(deps): update dependency @types/jest to v25 (#579) (505c1f0)
* chore(deps): update dependency jest to v25 (#572) (04dc9be)
* chore(deps): update all non-major dependencies (#571) (3d92737)
* chore(docs): fix typo in the comment: defualt -> default (#586) (78812db)

  release-it:conventional-changelog { increment: undefined,
  release-it:conventional-changelog   latestVersion: '6.5.0',
  release-it:conventional-changelog   isPreRelease: false,
  release-it:conventional-changelog   preReleaseId: undefined } +0ms
  release-it:conventional-changelog { err: null,
  release-it:conventional-changelog   result:
  release-it:conventional-changelog    { level: 1,
  release-it:conventional-changelog      reason: 'There are 0 BREAKING CHANGES and 1 features',
  release-it:conventional-changelog      releaseType: 'minor' } } +93ms
  release-it:conventional-changelog { changelog: '' } +104ms

Empty release notes
```

So there is git log here but no changelog from conventional-changelog plugin.

After debugging this for a while I've noticed that conventional-commits need a tag of the latest version to be set for it to generate the changelog. But here it seems we have a chicken and egg situation where the tag is generated (suggested) by the plugin so it's not yet set by the git plugin.

This problem seems to be very much like the old #145 one but back then I think there was no plugin for that yet so I thought things should have improved since then.

Do I still need to add some workarounds similar to what #145 describes (I haven't fully understood those yet)? And if so, shouldn't those things be handled by the plugin out of the box?

**Comment by webpro** [comment]
Things have improved since then, indeed, and you should not need such work-arounds anymore.

> After debugging this for a while I've noticed that conventional-commits need a tag of the latest version to be set for it to generate the changelog. But here it seems we have a chicken and egg situation where the tag is generated (suggested) by the plugin so it's not yet set by the git plugin.

The plugins do their jobs in "rounds", i.e. execute "init" for each plugin, then "bump", etc. ([more details](https://github.com/release-it/release-it/blob/master/docs/plugins.md#execution-order)). However, when the changelog is read by this plugin (`beforeRelease`), the tag is indeed not yet set by Git (`release`). This is by design.

This plugin is used by other projects (https://github.com/release-it/conventional-changelog/network/dependents), but I haven't heard of any that does not use the "angular" preset with this plugin. I don't expect this preset to be problematic, but it's possible. Note that this release-it plugin mainly delegates the hard work to, in this case, https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-conventionalcommits.

Incidentally, the first project from this list I open uses the "conventionalcommits" presets. Looking at its config and release notes for v4.0.0, it seems to work well (https://github.com/joshswan/react-native-globalize/releases).

So I'm not sure what to look for here. Can you maybe share your project, or is it closed?

**Comment by rchl** [comment]
So I have just forked the `react-native-globalize` project that you've linked and experimented on it. Turns out my problem was due to setting `npm: false` since that prevented `npm version` call. It works when I do `npm: { publish: false }` instead (in the real scenario, I will not even do that).

Thank you very much for your response and the project. :)

**Comment by webpro** [comment]
But you found a very interesting "dependency" for this plugin, which is the npm plugin. I didn't realize this the other, and I should update the docs about this. I'm a bit confused/surprised about whether conventional-changelog uses the Git tag or apparently the `package.json` version, I'll look into this shortly.
