### ISSUE TITLE
GitHub Release goes to origin vs. upstream remote

### ISSUE THREAD

**Issue by humphd** [release-it/release-it#632]
We ran into an issue today where a release seemed to use different remotes than we expected.

We got tags in our "upstream" repo for 0.8.0 and 0.8.1:

https://github.com/Seneca-CDOT/telescope/releases

However, the actual GitHub Release went to the "origin" of the dev who ran it (cc @Silvyre):

https://github.com/Silvyre/telescope/releases/tag/0.8.1

I would have expected them both to go to the same repo.

Our release-it config looks like this:

```json
{
  "hooks": {
    "before:init": ["npm run test-ci"]
  },
  "git": {
    "pushRepo": "upstream"
  },
  "github": {
    "release": true
  },
  "npm": {
    "publish": false
  }
}
```

With `github` I can specify the `pushRepo` but I don't see anything like that in https://github.com/release-it/release-it/blob/master/docs/github-releases.md.

Is this a config error on our part, a misunderstanding about what is expected, or a bug in release-it?

Thanks for any guidance on this.  We love release-it.

**Comment by humphd** [comment]
For reference, this is what his remotes look like:

![image](https://user-images.githubusercontent.com/427398/77689581-47d32500-6f78-11ea-88b4-15f60bcf4625.png)

And what he ran:

![image](https://user-images.githubusercontent.com/427398/77689644-66392080-6f78-11ea-823a-9b812dff0750.png)

**Comment by webpro** [comment]
The `git.pushRepo` is meant to specify which Git repo to push the changes.

You can use `github.pushRepo` as well (pretty sure, but didn't actually test). Didn't come across this use case yet. On first thought, I think it's good to explicitly specify this. Please let me know whether this works for you.

But definitely this should be documented, then.

**Comment by rchl** [comment]
I think that github release should be (by default) made to the same repo where (git) release is pushed. 

So if git release is made based on upstream branch, so should github release. And in this case, if `git.pushRepo` is specified as `upstream`, github release should follow that by default.

Otherwise, we have the same issue I was having in #608.

You see, how the user configures his repo and names his remotes shouldn't have bearing on where things get released. Otherwise, multiple people working on the same repo can end up making releases to different repos depending on whether they named their upstream remote `origin` or `upstream`.

**Comment by rchl** [comment]
(I have in fact made accidental github releases to wrong github repo due to this problem, since I've started using release-it recently :))

**Comment by webpro** [comment]
OK I guess that's clearly two votes in favor of using the same remote :)

**Comment by webpro** [comment]
Alright, the feature is in [v13.4.0](https://github.com/release-it/release-it/releases/tag/13.4.0)

**Comment by humphd** [comment]
@webpro thanks for doing this, I think it will remove confusion.

**Comment by webpro** [comment]
Yes, and it even cleaned up the codebase a bit 👍

**Comment by Silvyre** [comment]
The changes made fixed the issues we were having; thank you very much!
