### ISSUE TITLE
Check installed deps/devDeps?

### ISSUE THREAD

**Issue by rwjblue** [release-it/release-it#655]
I recently ran into a situation where I was releasing a newly merged PR, and forgot to run `npm ci` / `yarn install --frozen-lockfile`. The particular project at hand was published but its compiled output was incorrect (because I had forgotten to install the updated versions).

Would you be open to a PR that adds an additional validation to the `npm` plugin to confirm that the projects `dependencies`/`devDependencies` are properly installed? The actual logic there is "easy" (leveraging `semver` and `require('package-name/package')`), would run very quickly (requiring a few `.json` files is much faster than for example running `npm ci` / `yarn install --frozen-lockfile`), and would prevent some pretty _massive_ footgun scenarios. 

IMHO, this kind of check is very much in line with the spirit the checks that `git` does for checking dirty working directories and not having a remote setup.

@webpro - What do you think?

**Comment by webpro** [comment]
Interesting, I like this idea. But I also have some comments.

> but its compiled output was incorrect

Was there some kind of `npm run build` or something configured in a hook? I think it makes sense to also have `npm install` and/or `npm test` as a hook in this case.

> The actual logic there is "easy"

Yes it sounds easy enough, but isn't it more correct and error-proof and future-proof when using npm's mechanism directly (e.g. `npm install`)? If there's any mismatch it will be fixed by npm itself.

**Comment by rwjblue** [comment]
Ya, I think running `npm ci` / `yarn install --frozen-lockfile` would be good (and is in fact what `np` does).  Running the install would certainly fix the underlying issue just as well (and would not require the `release-it` user to do more work).

I assumed that you would prefer to just do a validation stage (based on the convo over in https://github.com/release-it/release-it/issues/96) similar to the other validation / guards that we do (e.g. are we logged in to npm, do we have unstaged work, is there a git upstream for this branch, etc).

Is the difference here that we can reasonably "do the right thing" (which is to run `npm ci` / `yarn install --frozen-lockfile`) whereas in those other circumstances we can't perfectly guess what the user is intending?

---

Either way, I'm happy to implement whichever why you think is best (I _personally_ would prefer `npm ci` / `yarn install` vs validation and erroring, because that feels like a better experience to me).

**Comment by rwjblue** [comment]
> Was there some kind of npm run build or something configured in a hook?

There are two common scenarios:

1. the case I was referring to in the issue description was via a `package.json` `prepare` script (nothing to do with `release-it` configuration).
2. the other common case, is that the tooling to actually do the release has been updated (e.g. `release-it` plugins, `release-it` itself). In this scenario there is no build per-se, but there could be a bug that exists in the release process because we are using out of date dependencies.

**Comment by webpro** [comment]
I'm a bit torn on this one...

- Usually, especially in a CI environment, this would be redundant.
- When release-it does `npm install` (or `npm ci` or `yarn install` or similar) by default, this adds quite some init time.
- The "manual validation" of packages is faster, but less good.

Uses have the most freedom when they just add exactly the command they want (e.g. `npm install` or similar) in some `init` hook. This way they can also more easily vary configurations across environments. I do understand the risk that people will first make the mistake, before finding out they can configure something here to prevent this from happening again. That's why I'm so torn here.

This kind of check is indeed similar to other plugin's prerequisite checks. It's hard to draw a line here. I try to be pragmatic here (usually thinking in terms of ROI: usefulness vs performance etc). Complexity/configurability. Btw I still need to add the "is collaborator" check in the npm plugin.

Maybe this should simply be documented well.
