### ISSUE TITLE
TypeError: Invalid Version

### ISSUE THREAD

**Issue by eMarek** [release-it/release-it#660]
Hey, I am trying to get "release-it" working, but I have some problems. Not sure where to start with explanation. I want to use it for releasing private project at GitLab. I don't want to publish it to npm. Base on this, my config file looks like this:
```json
{
  "git": {
    "commitMessage": "Release v${version}"
  },
  "gitlab": {
    "release": true
  },
  "npm": false
}
```
This is okay, right?

Second thing which I would like to say is that my package.json version is not prefixed with letter `v` (e.g.: `5.7.0`), but I use GIT release tags prefixed (e.g.: `v5.7.0`).
I guess that "release-it" supports that, right?

Okay here is first problem:
<img width="436" alt="Screenshot 2020-05-03 at 22 03 33" src="https://user-images.githubusercontent.com/311634/80925668-09f4c800-8d92-11ea-88a6-0508ce1d6da0.png">
Why are all my version numbers `null` and why it says I am currently at `unicorn`? This is one of my tag names which I use for something else. I guess "release-it" has mixed it for version number.

And second problem:
<img width="1229" alt="Screenshot 2020-05-03 at 22 04 00" src="https://user-images.githubusercontent.com/311634/80925697-43c5ce80-8d92-11ea-83fe-378212de4b06.png">
When I want to manually enter new version, it breaks. It looks like `unicorn` is the problem again. :D

My environment:
```
release-it: 13.5.7
dotenv-cli: 3.1.0
node: v12.16.1
```

Thanks in advance for any help.

**Comment by webpro** [comment]
> Base on this, my config file looks like this: [..] This is okay, right?

Yes, that config looks fine. However, the `version` from package.json is not used, because of `npm: false`. If you want to use/update the `version` from package.json, but not publish to npm, use this ([docs on npm](https://github.com/release-it/release-it/blob/master/docs/npm.md)):

```
{
  "npm: {
    "publish": false
  }
}
```

> Second thing which I would like to say is that my package.json version is not prefixed with letter v (e.g.: 5.7.0), but I use GIT release tags prefixed (e.g.: v5.7.0).
> I guess that "release-it" supports that, right?

Yes, the version and the tag are two different variables for release-it. The latest tag is found, and release-it automatically re-uses the tag prefix. You can also explicitly provide this in the configuration:

```
{
  "git": {
    "tagName": "v${version}"
  }
}
```

> Why are all my version numbers `null` and why it says I am currently at `unicorn`?

See [Latest version](https://github.com/release-it/release-it/blob/master/README.md#latest-version). So probably the latest tag is `unicorn`.

> When I want to manually enter new version, it breaks. It looks like `unicorn` is the problem again. :D

That looks like a bug to me. I'll look into it, thanks!

**Comment by eMarek** [comment]
Turned out that changing `.release-it.json` config file from
```
{
  "npm": false
}
```
to
```
{
  "npm: {
    "publish": false
  }
}
```
solved my problem.

I am closing this thread since my issue was resolved. Feel free to reopen it if you think there is still a bug.
