### ISSUE TITLE
Tag types

### ISSUE THREAD

**Issue by alex529** [release-it/release-it#680]
Hi, this is more a question than an actual issue, issue I've tried to read the doc could not figure it out.
Is it possible to change the tag type that release-it does(from annotated to lightweight), we're using CircleCI and which does a shallow clone, and triggering on annotated tags doesn't work properly.

**Comment by webpro** [comment]
By default, release-it does this:

```
git tag --annotate --message [message] [extraArgs] [tagName]
```

So you can set `git.tagArgs`, but I'm not sure whether this could help you.

**Comment by alex529** [comment]
I would like to remove the 2 args `--annotate --message` as this is what creates the issue with CircleCI, if i filter by tags, it makes a shallow copy of the repository and it doesn't get the commit that the tag points to.
Is this something that you are planning to support?

**Comment by webpro** [comment]
It sounds more like Circle CI has an issue by not supporting proper tags in this regard, right?

Full annotated tags are a good practice, lightweight tags are not recommended (also see https://git-scm.com/book/en/v2/Git-Basics-Tagging). Also since this would be a breaking change, I'm not very fond of the idea tbh.

**Comment by alex529** [comment]
This was more on the line that you should not enforce behaviour upon the user of the tool, having sensible defaults makes sens, but allowing the user to change them makes more sens to me.
I will work around this issue in the CircleCI pipeline.
