### ISSUE TITLE
Release-it won't work out of a docker container - Permission denied (publickey).

### ISSUE THREAD

**Issue by ilmoi** [release-it/release-it#698]
Beginner dev here. I got release-it working from my machine no problem but when I try to run from of a docker container I get the following:

```
ERROR Unable to fetch from git@github.com:nectar-cs/nectl.git
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

This (righly) goes away when I create an `id_rsa.pub` inside the container and add it to my github account. But I obviously wouldn't want to do that every time I run my CI/CD pipeline. From reading the docs I got the impression that the `GITHUB_TOKEN` env variable is everything that `release-it` needs to work, yet I'm getting the above error with the variable set.

What am I missing? It's a fresh linux container with fresh git. Is there some sort of setting or flag I need to flip to tell it to use the token instead of ssh?

**Comment by webpro** [comment]
1. The `GITHUB_TOKEN` is necessary for the GitHub Release (with the GitHub REST API).
2. Since this requires a tag on the GitHub remote, Git itself is needed for the `git tag` and `git push` (and release-it does a `git fetch` initially as well). For Git, the public key is recommended (to push over SSH).

So yeah, you need both the token (GH Release) and the public key (Git transport over SSH).

Also see https://github.com/release-it/release-it/blob/master/docs/ci.md

**Comment by ilmoi** [comment]
Understood, thank you!
