### ISSUE TITLE
use job-token instead of private-token in gitlab header

### ISSUE THREAD

**Issue by niekvandael** [release-it/release-it#736]
**RFE**

When running release-it from a gitlab pipeline, we need to use CI_JOB_TOKEN to authenticate via job-token header parameter.
The current implementation of release-it only supports the private-token header.

Is there any way to select the job-token header instead of private-token header?

GitLab.js line #28
      headers: {
        'user-agent': 'webpro/release-it',
        '**Private-Token**': this.token
      }

Should change to (on ci-builds):
      headers: {
        'user-agent': 'webpro/release-it',
        '**Job-Token**': this.token
      }

Thanks.

**Comment by webpro** [comment]
Thanks @niekvandael.

Looks like we have (at least) three options here:

1. Set both headers (with the same value). Con: (security) issues? Pro: little implementation risks, no configuration for users.
1. Another option is to automatically switch based on the presence of the `CI_JOB_TOKEN` environment variable. Con: there's a chance of wrong determination? E.g. somebody sets variable this on local machine. Pro: no configuration for users.
1. Otherwise it could become a configuration option, such as `gitlab.tokenHeader`. Con: users need to set this based on environment. Pro: little implementation risks.

I have just released `release-it@next` (version 14.4.0-next.0), which implements the second option. Could you give this a shot please?

**Comment by niekvandael** [comment]
Hi @webpro ,

I can confirm the release-it@next version 14.4.0-next.0 works fine in combination with CI_JOB_TOKEN.
Option 2 could indeed produce unsuspected behaviour indeed as you mention, but if documented well, it should be OK, right?

Thank you!

**Comment by webpro** [comment]
Thanks for the feedback! Release in v14.4.0
