### ISSUE TITLE
Use ${version} as part of GitHub asset name

### ISSUE THREAD

**Issue by sqwk** [release-it/release-it#759]
"github": {
        "assets": ["dist/somefile-v${version}.zip"],
    }

Is it possible to use a variable (the version number) as part of a name to upload files to a GitHub release? At the moment this fails silently and does not upload anything.

**Comment by webpro** [comment]
At the moment this is not possible, as this represents a "glob". In your case it's not matching anything. It should print a warning when there are matching files, though. You can use wildcards (release-it uses [globby](https://www.npmjs.com/package/globby) under the hood), but make sure not to upload old versions with the release.

**Comment by ivandov** [comment]
I just hit this exact issue. I have a hook to build a `.tar.gz` before the github release step:

```
before:github:release:
    - ansible-galaxy collection build --output-path ./dist
```

Since the version number is dynamically set with the `bumper` plugin, I want to be able to only upload the asset that was just built, and keep around old builds locally. 

Seems like the only workaround I have for now is to delete old builds before a new release so I can do a wildcard match.

Or maybe output the build to two different folders, keeping one `dist-latest` with the version I want to upload, and a `dist-all` with all versions. 

It'd be nice to support the direct `-v${version}` value being passed in... sounds like you'd just need to evaluate the `${version}` before sending to `globby`, right?

**Comment by ivandov** [comment]
This is my current workaround, in case it's helpful for anyone else:

```
before:github:release:
    - ansible-galaxy collection build --output-path ./dist/latest
  after:release:
    - mv ./dist/latest/* ./dist/.
github:
  assets:
    - dist/latest/ibm-simple-plays-*.tar.gz
```

Excuse the YAML format - using it for Ansible content, so just makes sense to keep it YAML instead of JSON.

**Comment by webpro** [comment]
This feature is now in [v14.10.0](https://github.com/release-it/release-it/releases/tag/14.10.0), please let me know if you encounter any issues, thanks.

**Comment by sqwk** [comment]
Just tested this. Seems to work fine. Thanks for the quick turnaround.
