### ISSUE TITLE
Github Release - 400 Bad Request: Must specify access token via Authorization header

### ISSUE THREAD

**Issue by JTambunt** [release-it/release-it#762]
Apologies in advance if this issue is out of scope.

As of today github no longer supports using 'access_token' in the query param: https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/

Here's a screenshot when I attempt to use release-it for the github release:
<img width="1540" alt="Screen Shot 2021-05-05 at 7 09 10 PM" src="https://user-images.githubusercontent.com/11169193/117220978-5bd19300-add6-11eb-953c-2db99be25e8b.png">

Is this something I need to fix on my end or something internal to release-it?

**Comment by webpro** [comment]
This surprise me, as release-it uses the [Octokit](https://github.com/octokit/rest.js) client while explicitly setting the `auth` header and not any query params:

https://github.com/release-it/release-it/blob/6164e54a06006769ff7f5082b8fb90e3a6e1e315/lib/plugin/github/GitHub.js#L132-L156

Maybe tomorrow I have some more time to dig into this. Not sure where the problem is atm!

**Comment by JTambunt** [comment]
I am terribly sorry but it looks like after updating my package version it went away (must have pointed to an older version of Octokit). Thank you so much for looking into this, sorry for using your time.
