### ISSUE TITLE
How it works with protected branch?

### ISSUE THREAD

**Issue by mHamza301** [release-it/release-it#823]
I want to know one thing what happens when the branch protection is enabled?

Like in the case of semantic-release we need to get a PAT with admin-level access. What is the scenario with release-it?

**Comment by newfunda** [comment]
When branch protection is on which is ideal thing to do so that no one pushes the code until PR is created and reviewed, same is the case with release-it which is given in the error below:

Changeset:
M CHANGELOG.md
M package.json

Git commit
✔ Git commit
Git tag
✔ Git tag
Git push
✖ Git push
ERROR remote: error: GH006: Protected branch update failed for refs/heads/master.

Now, in case we use semantic-release with PAT with admin access also does it creates PR and auto review and merge to master ?

with release-it also I pass admin level PAT using GITHUB_TOKEN, NPM_TOKEN etc.. using PAT from GitHub with repo and package creation access, even then it is asking about PR needed and at least one reviewer needed and all status checks to be passed before it can merge to master.

**Comment by webpro** [comment]
First, it's good to understand that release-it uses separate plugins for Git and GitHub operations:

- The [Git plugin](https://github.com/release-it/release-it/blob/master/docs/git.md) does the Git commit, tag and push operations. This is executed using Git from the shell (`git commit` etc.) and authorized by an SSH key.
- The [GitHub plugin](https://github.com/release-it/release-it/blob/master/docs/github-releases.md) does the GitHub Release. Such a release requires the Git tag to be present on the origin (GitHub), that's why the Git tag and push happens first. Creating a GitHub Release is done by GitHub's Octokit REST client, and authorized by the `GITHUB_TOKEN`.

Now, when GitHub branch protection is activated for e.g. the master branch, pushing to this branch (using `git push`) is protected (depending on the settings in GitHub). This is based on the access that the `git` client has (over SSH). It might be possible to use an SSH key for an admin user to overrule the protection (I don't know). However, this has nothing to do with the PAT (`GITHUB_TOKEN`) that is used by the plugin to do GitHub releases.
