### ISSUE TITLE
git.requireCommits true exits with an error code

### ISSUE THREAD

**Issue by sinkovsky** [release-it/release-it#832]
When in CI context this behaviour breaks the build.

Desired behaviour
When branch is merged, release is triggered.
Release commit to the same branch triggers the build again and with requireCommits set to 'true' it should skip the build.

Problem
release-it exits with an error code and message
```
ERROR There are no commits since the latest tag.
Documentation: https://git.io/release-it-git
```
This marks Jenkins build as `failed`.

Workaround
release-it && exit 0

Problem with this approach is that it will hide all other errors

**Comment by webpro** [comment]
Yeah, this is tricky. What is expected behavior here? One could also argue/expect that it should never silently exit without a successful release. Happy to consider this for a next major release, though. Are you aware of any best practices around this topic?

An option could also be for release-it to use specific exit codes (other than `1`), then you can ignore them specifically.
