### ISSUE TITLE
Caution about doing npm { publish: true } locally

### ISSUE THREAD

**Issue by webketje** [release-it/release-it#866]
I think it might be worth it to caution users for a common pitfall.
On NPM, packages with a higher quality [npms.io](https://npms.io) rating score better.

When running release-it locally, it is important to set `npm: { publish: false }` in the `.release-it.json`.
This is because quality score is computed according to test results, coverage & other factors.
When you publish the package to NPM locally in-between npm version,changelog, commit, tag, obviously those stats are not available online yet for the tag you just created (on a service like coveralls.io, travis-ci.com, GH actions etc).

_NB: Logically, the NPM publish step should happen last. If a user bails out of the release-it process with Ctrl+C halfway, but after the NPM step, because they suddenly think of a crucial thing that they forgot to include, it's too late. The version is irreversibly published to NPM_

To demonstrate the impact:
* [metalsmith-handlebars-x](https://npms.io/search?q=%40metalsmith-handlebars-x) is a package I published using `npm: { publish: true }`. It had 100% test coverage & successful tests. Yet, its quality rating is only **69%**.
* [@metalsmith/remove](https://npms.io/search?q=%40metalsmith%2Fremove) is a package I published using `npm: { publish: false }`.
It "only" has 92% coverage. Yet, its quality rating is a whopping **98%**.

*Note that another factor is the stability, in this case the lowest rated package has a 0.x version which also has an impact on the score*

**Comment by webpro** [comment]
> the NPM publish step should happen last.

This was actually release-it's behavior a few major versions back. However, for the release-it process itself, most issues come from the `npm publish` step, so that's why this plugin's release step is executed before the release steps of e.g. `git` and `github`.

For instance, pushing a tag first could just as well result in other external tooling/services triggers (which could potentially be an issue before the package is available in a registry). Cancellation or exceptions can be just as problematic with a different order. I feel the current order is the least problematic for most situations, but I don't have actual data to back it up (just some valid reasonings I agreed to a few years back after which I changed it).

Since the order of execution is based on a simple array of plugins, it may be feasible to make this configurable. I'm open to a PR for this.

**Comment by webketje** [comment]
@webpro thx for explaining the rationale! I still believe an accidental NPM publish is the worst that could happen for OSS, but I didn't consider private registries (eg using Nexus or Verdaccio) where if you have access to the server, an NPM publish is not *that* irreversible. 

When you mentioned the execution is an array of plugins, I thought maybe the "accidental" forward can be solved more easily in a different way, e.g. a confirmation "final-prompt" plugin that asks a yes/no question before "it could be too late". Is it possible to have the plugin sequence run as with `--dry-run`, but queuing the sequence and executing them all at once at the end? 
release-it just makes package maintenance such a breeze that I sometimes accidentally tap forward too fast on autopilot 😄

The main "issue" was about including a note in the npm part of the docs for public NPM registry package authors who run release-it locally & care about the package quality rating. I'll make a PR proposal for this

**Comment by webpro** [comment]
> I still believe an accidental NPM publish is the worst that could happen for OSS

Oops, I got carried away by that single statement I quoted before. I do understand your point of view, and I agree with the "irreversibility" argument (including private registries). That's why it could be interesting to look into configuring the order of things.

> [...] queuing the sequence and executing them all at once at the end?

That's basically what happens already. The hooks are there to run QA first and in the UI you see the changelog before proceeding. Also see:

- https://github.com/release-it/release-it/blob/master/README.md#hooks
- https://github.com/release-it/release-it/blob/master/docs/plugins.md#execution-order

There's also the `--only-version` flag to only prompt for the first question, and confirm the rest of the prompts automatically. Things combined I would think this is kind of similar as to what you are asking for here.

> The main "issue" was about including a note in the npm part of the docs for public NPM registry package authors who run release-it locally & care about the package quality rating. I'll make a PR proposal for this

Good idea, much appreciated!
