### ISSUE TITLE
Update PRs included in release

### ISSUE THREAD

**Issue by kenske** [release-it/release-it#959]
I'd like to replicate one of the features that `semantic-release` has, which is to comment on PRs when a release is created. The comment says something like "These changes were released in x.x.x". Is there a way to do this with `release-it`? I looked through the documentation but I couldn't find it. I also looked through the plugins and couldn't find anything like this.

**Comment by webpro** [comment]
Unfortunately release-it has no such feature indeed.

It is an interesting feature, though, so I'll leave this open. However it's not high on my list of priorities. If you or anyone else is interested in creating this, I'm happy to discuss further.

**Comment by webpro** [comment]
Darn, I should've added "closes "959" when I pushed b22ac2004c51aebfdee965707e7db112d46331d2 to it off!

Anyway, this is available now, also see https://github.com/release-it/release-it/blob/main/docs/github-releases.md#comments

**Comment by virtuallyunknown** [comment]
> Darn, I should've added "closes #959" when I pushed [b22ac20](https://github.com/release-it/release-it/commit/b22ac2004c51aebfdee965707e7db112d46331d2) to show it off!
> 
> Anyway, this is available now, also see https://github.com/release-it/release-it/blob/main/docs/github-releases.md#comments

Hey, I am wondering if this feature is working, or perhaps I am doing something incorrectly?

https://github.com/virtuallyunknown/npm-publish-test/blob/master/package.json#L49

My `GITHUB_TOKEN` env variable is working correctly, I can tell because [a release is generated automatically](https://github.com/virtuallyunknown/npm-publish-test/releases/tag/0.2.8) after I run `release-it`, otherwise a browser tab would open where you have to do it manually.

But then there is no comment on [merged pull requests](https://github.com/virtuallyunknown/npm-publish-test/pull/9).

If I am doing something incorrectly, I apologize in advance.

**Comment by webpro** [comment]
Not sure. So far I've been using this feature in this release-it repo and https://github.com/webpro/knip without any hiccups.

You might want to check output closely and see if anything is off (https://github.com/release-it/release-it#troubleshooting--debugging)

**Comment by virtuallyunknown** [comment]
> Not sure. So far I've been using this feature in this release-it repo and https://github.com/webpro/knip without any hiccups.
> 
> You might want to check output closely and see if anything is off (https://github.com/release-it/release-it#troubleshooting--debugging)

Thanks for the tips, I somehow managed to miss the fact you can run `release-it` with debugging enabled. With `"verbose": 2` and `NODE_DEBUG=release-it:*` I am seeing at the very end that a request is being made towards the github api:

[https://api.github.com/search/issues?q=repo%3Avirtuallyunknown%2Fnpm-publish-test+type%3Apr+is%3Amerged+7439ee7+2656ca3+86077b8](https://api.github.com/search/issues?q=repo%3Avirtuallyunknown%2Fnpm-publish-test+type%3Apr+is%3Amerged+7439ee7+2656ca3+86077b8)

The status code is success 200, but that's pretty much it. The next line of `release-it` gives me a link to my release and the command exits.

```
GET /search/issues?q=repo%3Avirtuallyunknown%2Fnpm-publish-test+type%3Apr+is%3Amerged+7439ee7+2656ca3+86077b8 - 200 in 266ms
🔗 https://github.com/virtuallyunknown/npm-publish-test/releases/tag/0.3.0
🏁 Done (in 21s.)
```

I checked out `knip` and my setup seems almost the same. Is there any specific process that needs to be followed when handling PRs? I just follow the instructions provided by GitHub:

![image](https://github.com/release-it/release-it/assets/24871108/dfc85d88-522b-468c-9ec7-6b27d8eec34e)

I then run `release-it` and the end result is what I just explained above, but no comments being made.

**Comment by webpro** [comment]
That's odd. For both repos I'm always running release-it from the command-line, so the same `GITHUB_TOKEN`/user to do both the GitHub Release and submitting the issue/PR comments. If there was an issue, e.g. with token/rights it should throw an exception. I'm also not doing anything special when merging commits. Did you try with commits that have something like `closes #1` in a commit message being merged and released and see if that works?

**Comment by virtuallyunknown** [comment]
> For both repos

Sorry, I am not sure I understand what you meant by **both** repos?

But, that aside, I just tested what you recommended, and take please a look, it worked:

[https://github.com/virtuallyunknown/npm-publish-test/pull/3](https://github.com/virtuallyunknown/npm-publish-test/pull/3)

What I did was that when I merged the PR with the master branch, I set `fix: closes #3` as a my commit message, so apparently that triggers some internal logic, and when I ran `release-it` there was a `POST` request made towards the github api:

```
GET /search/issues?q=repo%3Avirtuallyunknown%2Fnpm-publish-test+type%3Apr+is%3Amerged+c8374aa+bd5b2ac - 200 in 264ms
request {
  method: 'POST',
  baseUrl: 'https://api.github.com',
  headers: {
    accept: 'application/vnd.github.v3+json',
    'user-agent': 'release-it/15.10.3 octokit-rest.js/19.0.7 octokit-core.js/4.2.1 Node.js/19.9.0 (linux; x64)'
  },
  mediaType: { format: '', previews: [] },
  request: {
    timeout: 0,
    fetch: [AsyncFunction: fetch],
    hook: [Function: bound bound register]
  },
  url: '/repos/{owner}/{repo}/issues/{issue_number}/comments',
  owner: 'virtuallyunknown',
  repo: 'npm-publish-test',
  issue_number: 3,
  body: ':rocket: _This issue has been resolved in v0.3.2. See [Release 0.3.2](https://github.com/virtuallyunknown/npm-publish-test/releases/tag/0.3.2) for release notes._'
}
POST /repos/virtuallyunknown/npm-publish-test/issues/3/comments - 201 in 799ms
```

I think at the end of the day it's my lack of knowledge that was the problem, since I am not very experienced with this (public git repositories, PRs etc.), otherwise I would've remembered that it's common to write `closes ....` in commit messages.

That said, I think it would be really nice to know the exact criterion/logic under which `comments.submit: true` triggers.

**Comment by virtuallyunknown** [comment]
Okay, so I've done some code digging, and found the "culprits".

https://github.com/release-it/release-it/blob/main/lib/plugin/github/util.js#L36
https://github.com/pvdlg/issue-parser/blob/master/lib/hosts-config.js#L5

but after doing some [additional research](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword), I see that having the option to omit these keywords is probably not the best idea.

Cheers!

**Comment by webpro** [comment]
Glad you sorted it out and thanks for all the details. I'll update the docs to make it more clear.
