### ISSUE TITLE
Even if private registry is used, log refers to npmjs.com

### ISSUE THREAD

**Issue by cakeinpanic** [release-it/release-it#997]
Hi, first of all thank you for the great package, I love it!

Noticed this: I am using private registry(it's set in `.npmrc`), and release works smooth, however log says this
```
🔗 https://www.npmjs.com/package/yotpo-dependabot-test
```
which is misleading

As an easy fix I suggest to support one more config property `npm.privateRegistry : boolean` and do not post a link to a package if it's set to true. WDYT?

**Comment by webpro** [comment]
Currently release-it reads only `publishConfig.registry` and falls back to the default registry.

Looks like we can use `npm config get registry` to read that value if it's in `.npmrc`, so that could be another way to approach this without needing more config. WDYT?

Any chance you're up for a PR? Otherwise I'll pick it up within a week or so.

Thanks for the kind words :)
